░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░██╗░░░░░██╗██╗░░░██╗███████╗░██████╗███╗░░░███╗██████╗░░░░░░
░░░░░██║░░░░░██║██║░░░██║██╔════╝██╔════╝████╗░████║██╔══██╗░░░░░
░░░░░██║░░░░░██║╚██╗░██╔╝█████╗░░╚█████╗░██╔████╔██║██████╔╝░░░░░
░░░░░██║░░░░░██║░╚████╔╝░██╔══╝░░░╚═══██╗██║╚██╔╝██║██╔═══╝░░░░░░
░░░░░███████╗██║░░╚██╔╝░░███████╗██████╔╝██║░╚═╝░██║██║░░░░░░░░░░
░░░░░╚══════╝╚═╝░░░╚═╝░░░╚══════╝╚═════╝░╚═╝░░░░░╚═╝╚═╝░░░░░░░░░░
░░░░░░░░░░░█████╗░░█████╗░███╗░░██╗███████╗██╗░██████╗░░░░░░░░░░░
░░░░░░░░░░██╔══██╗██╔══██╗████╗░██║██╔════╝██║██╔════╝░░░░░░░░░░░
░░░░░░░░░░██║░░╚═╝██║░░██║██╔██╗██║█████╗░░██║██║░░██╗░░░░░░░░░░░
░░░░░░░░░░██║░░██╗██║░░██║██║╚████║██╔══╝░░██║██║░░╚██╗░░░░░░░░░░
░░░░░░░░░░╚█████╔╝╚█████╔╝██║░╚███║██║░░░░░██║╚██████╔╝░░░░░░░░░░
░░░░░░░░░░░╚════╝░░╚════╝░╚═╝░░╚══╝╚═╝░░░░░╚═╝░╚═════╝░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░                                                               ░
░ This is the config file for the LiveSMP server, changes will  ░
░ only take effect after a server restart or a reload           ░
░                                                               ░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

