main: nl.xanderwander.livesmp.Main
name: LiveSMP
version: 0.0.1
authors: [XanderWander, Lego_freak1999]
api-version: 1.17
load: POSTWORLD
depend: [KotlinLib, LuckPerms]
commands:
  menu:
    description: Open menus
  slapen:
    description: Slaap command
  resourcepack:
    description: Load latest resourcepack
  rp:
    description: Load latest resourcepack
  rrp:
    description: unload resourcepack
  admin:
    description: Admin menu
  adminmode:
    description: Use admin mode